In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.subplots as make_subplots

# Load DataSet

In [14]:
world_ranking = pd.read_csv("/content/fifa_ranking_2022-10-06 - fifa_ranking_2022-10-06.csv.csv")
matche = pd.read_csv("/content/matches_1930_2022 - matches_1930_2022.csv.csv")
world_cup = pd.read_csv("/content/world_cup - world_cup.csv.csv")

In [15]:
world_ranking.head() # 2018 to 2022

,team,team_code,association,rank,previous_rank,points,previous_points
0,Brazil,BRA,CONMEBOL,1,1,1841.30,1837.56
1,Belgium,BEL,UEFA,2,2,1816.71,1821.92
2,Argentina,ARG,CONMEBOL,3,3,1773.88,1770.65
3,France,FRA,UEFA,4,4,1759.78,1764.85
4,England,ENG,UEFA,5,5,1728.47,1737.46

In [16]:
world_cup.head()

,Year,Host,Teams,Champion,Runner-Up,TopScorrer,Attendance,AttendanceAvg,Matches
0,2022,Qatar,32,Argentina,France,Kylian Mbappé - 8,3404252,53191,64
1,2018,Russia,32,France,Croatia,Harry Kane - 6,3031768,47371,64
2,2014,Brazil,32,Germany,Argentina,James Rodríguez - 6,3429873,53592,64
3,2010,South Africa,32,Spain,Netherlands,"Wesley Sneijder, Thomas Müller... - 5",3178856,49670,64
4,2006,Germany,32,Italy,France,Miroslav Klose - 5,3352605,52384,64

In [17]:
matche.head()

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

# Info

In [18]:
matche.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    object
 1   away_team                        964 non-null    object
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    object
 9   home_captain                     644 non-null    object
 10  away_manager                     964 non-null    object
 11  away_captain                     644 non-null    object
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    object
 14  Officials                        709 non-null    object
 15  Round                            964 non-null    object
 16  Date                             964 non-null    object
 17  Score                            964 non-null    object
 18  Referee                          709 non-null    object
 19  Notes                            73 non-null     object
 20  Host                             964 non-null    object
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    object
 23  away_goal                        571 non-null    object
 24  home_goal_long                   718 non-null    object
 25  away_goal_long                   571 non-null    object
 26  home_own_goal                    39 non-null     object
 27  away_own_goal                    17 non-null     object
 28  home_penalty_goal                116 non-null    object
 29  away_penalty_goal                84 non-null     object
 30  home_penalty_miss_long           6 non-null      object
 31  away_penalty_miss_long           9 non-null      object
 32  home_penalty_shootout_goal_long  34 non-null     object
 33  away_penalty_shootout_goal_long  34 non-null     object
 34  home_penalty_shootout_miss_long  24 non-null     object
 35  away_penalty_shootout_miss_long  30 non-null     object
 36  home_red_card                    51 non-null     object
 37  away_red_card                    54 non-null     object
 38  home_yellow_red_card             23 non-null     object
 39  away_yellow_red_card             31 non-null     object
 40  home_yellow_card_long            621 non-null    object
 41  away_yellow_card_long            627 non-null    object
 42  home_substitute_in_long          740 non-null    object
 43  away_substitute_in_long          747 non-null    object
dtypes: float64(4), int64(4), object(36)
memory usage: 331.5+ KB

In [19]:
world_ranking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   team             211 non-null    object
 1   team_code        211 non-null    object
 2   association      211 non-null    object
 3   rank             211 non-null    int64
 4   previous_rank    211 non-null    int64
 5   points           211 non-null    float64
 6   previous_points  211 non-null    float64
dtypes: float64(2), int64(2), object(3)
memory usage: 11.7+ KB

# access the column

In [20]:
matche['home_goal'] # access the whole column

0                 Ángel Di María · 36|Lionel Messi · 108
1                   Joško Gvardiol · 7|Mislav Oršić · 42
2              Theo Hernández · 5|Randal Kolo Muani · 79
3                Julián Álvarez · 39|Julián Álvarez · 69
4                                 Youssef En-Nesyri · 42
                             ...
959                                      Luis Monti · 81
960               Aleksandar Tirnanić · 21|Ivan Bek · 30
961    Adalbert Deșu · 1|Constantin Stanciu · 79|Nico...
962    Bart McGhee · 23|Tom Florie · 45|Bert Patenaud...
963    Lucien Laurent · 19|Marcel Langiller · 40|Andr...
Name: home_goal, Length: 964, dtype: object

# access the column one row

In [21]:
matche["home_goal"][0] # only access the one row of the specify column

'Ángel Di María · 36|Lionel Messi · 108'

# Shape

In [22]:
print(world_ranking.shape)
print(matche.shape)
print(world_cup.shape)

(211, 7)
(964, 44)
(22, 9)

# Check Null Values in the data set

In [23]:
print(world_ranking.isnull().sum())

team               0
team_code          0
association        0
rank               0
previous_rank      0
points             0
previous_points    0
dtype: int64

In [24]:
print(world_cup.isnull().sum())

Year             0
Host             0
Teams            0
Champion         0
Runner-Up        0
TopScorrer       0
Attendance       0
AttendanceAvg    0
Matches          0
dtype: int64

In [25]:
matche.isnull().sum()

home_team                            0
away_team                            0
home_score                           0
home_xg                            836
home_penalty                       929
away_score                           0
away_xg                            836
away_penalty                       929
home_manager                         0
home_captain                       320
away_manager                         0
away_captain                       320
Attendance                           0
Venue                                0
Officials                          255
Round                                0
Date                                 0
Score                                0
Referee                            255
Notes                              891
Host                                 0
Year                                 0
home_goal                          246
away_goal                          393
home_goal_long                     246
away_goal_long                     393
home_own_goal                      925
away_own_goal                      947
home_penalty_goal                  848
away_penalty_goal                  880
home_penalty_miss_long             958
away_penalty_miss_long             955
home_penalty_shootout_goal_long    930
away_penalty_shootout_goal_long    930
home_penalty_shootout_miss_long    940
away_penalty_shootout_miss_long    934
home_red_card                      913
away_red_card                      910
home_yellow_red_card               941
away_yellow_red_card               933
home_yellow_card_long              343
away_yellow_card_long              337
home_substitute_in_long            224
away_substitute_in_long            217
dtype: int64

In [26]:
matche.isnull().sum()/len(matche)*100  # check the null value percentage (who many null value in this data)

home_team                           0.000000
away_team                           0.000000
home_score                          0.000000
home_xg                            86.721992
home_penalty                       96.369295
away_score                          0.000000
away_xg                            86.721992
away_penalty                       96.369295
home_manager                        0.000000
home_captain                       33.195021
away_manager                        0.000000
away_captain                       33.195021
Attendance                          0.000000
Venue                               0.000000
Officials                          26.452282
Round                               0.000000
Date                                0.000000
Score                               0.000000
Referee                            26.452282
Notes                              92.427386
Host                                0.000000
Year                                0.000000
home_goal                          25.518672
away_goal                          40.767635
home_goal_long                     25.518672
away_goal_long                     40.767635
home_own_goal                      95.954357
away_own_goal                      98.236515
home_penalty_goal                  87.966805
away_penalty_goal                  91.286307
home_penalty_miss_long             99.377593
away_penalty_miss_long             99.066390
home_penalty_shootout_goal_long    96.473029
away_penalty_shootout_goal_long    96.473029
home_penalty_shootout_miss_long    97.510373
away_penalty_shootout_miss_long    96.887967
home_red_card                      94.709544
away_red_card                      94.398340
home_yellow_red_card               97.614108
away_yellow_red_card               96.784232
home_yellow_card_long              35.580913
away_yellow_card_long              34.958506
home_substitute_in_long            23.236515
away_substitute_in_long            22.510373
dtype: float64

# Duplication

In [27]:
print(world_ranking.duplicated().sum())
print(matche.duplicated().sum())
print(world_cup.duplicated().sum())

0
0
0

# combine the column

In [28]:
print(matche['home_team'].unique())

['Argentina' 'Croatia' 'France' 'Morocco' 'England' 'Netherlands'
 'Portugal' 'Japan' 'Brazil' 'Korea Republic' 'Ghana' 'Cameroon' 'Serbia'
 'Canada' 'Costa Rica' 'Australia' 'Tunisia' 'Saudi Arabia' 'Poland'
 'Ecuador' 'IR Iran' 'Wales' 'Belgium' 'Spain' 'Qatar' 'Switzerland'
 'Uruguay' 'Germany' 'Denmark' 'Mexico' 'Senegal' 'United States' 'Sweden'
 'Russia' 'Colombia' 'Panama' 'Iceland' 'Nigeria' 'Peru' 'Egypt' 'Algeria'
 'Bosnia and Herzegovina' 'Honduras' 'Italy' 'Greece' "Côte d'Ivoire"
 'Chile' 'Paraguay' 'Korea DPR' 'Slovakia' 'Slovenia' 'South Africa'
 'New Zealand' 'Ukraine' 'Togo' 'Czech Republic' 'Serbia and Montenegro'
 'Angola' 'Trinidad and Tobago' 'Türkiye' 'China PR' 'Republic of Ireland'
 'Romania' 'Scotland' 'FR Yugoslavia' 'Jamaica' 'Bulgaria' 'Bolivia'
 'Norway' 'West Germany' 'Yugoslavia' 'Czechoslovakia' 'Austria'
 'United Arab Emirates' 'Soviet Union' 'Northern Ireland' 'Iraq' 'Hungary'
 'Germany DR' 'Zaire' 'Haiti' 'Cuba']

In [29]:
matche['home_team'] = matche['home_team'].apply(lambda x: x.replace("Germany DR","West Germany"))
matche['home_team'].unique()

array(['Argentina', 'Croatia', 'France', 'Morocco', 'England',
       'Netherlands', 'Portugal', 'Japan', 'Brazil', 'Korea Republic',
       'Ghana', 'Cameroon', 'Serbia', 'Canada', 'Costa Rica', 'Australia',
       'Tunisia', 'Saudi Arabia', 'Poland', 'Ecuador', 'IR Iran', 'Wales',
       'Belgium', 'Spain', 'Qatar', 'Switzerland', 'Uruguay', 'Germany',
       'Denmark', 'Mexico', 'Senegal', 'United States', 'Sweden',
       'Russia', 'Colombia', 'Panama', 'Iceland', 'Nigeria', 'Peru',
       'Egypt', 'Algeria', 'Bosnia and Herzegovina', 'Honduras', 'Italy',
       'Greece', "Côte d'Ivoire", 'Chile', 'Paraguay', 'Korea DPR',
       'Slovakia', 'Slovenia', 'South Africa', 'New Zealand', 'Ukraine',
       'Togo', 'Czech Republic', 'Serbia and Montenegro', 'Angola',
       'Trinidad and Tobago', 'Türkiye', 'China PR',
       'Republic of Ireland', 'Romania', 'Scotland', 'FR Yugoslavia',
       'Jamaica', 'Bulgaria', 'Bolivia', 'Norway', 'West Germany',
       'Yugoslavia', 'Czechoslovakia', 'Austria', 'United Arab Emirates',
       'Soviet Union', 'Northern Ireland', 'Iraq', 'Hungary', 'Zaire',
       'Haiti', 'Cuba'], dtype=object)

In [30]:
matche['home_team'] = matche['home_team'].apply(lambda x: x.replace("East Germany","Germany"))
matche['home_team'].unique()

array(['Argentina', 'Croatia', 'France', 'Morocco', 'England',
       'Netherlands', 'Portugal', 'Japan', 'Brazil', 'Korea Republic',
       'Ghana', 'Cameroon', 'Serbia', 'Canada', 'Costa Rica', 'Australia',
       'Tunisia', 'Saudi Arabia', 'Poland', 'Ecuador', 'IR Iran', 'Wales',
       'Belgium', 'Spain', 'Qatar', 'Switzerland', 'Uruguay', 'Germany',
       'Denmark', 'Mexico', 'Senegal', 'United States', 'Sweden',
       'Russia', 'Colombia', 'Panama', 'Iceland', 'Nigeria', 'Peru',
       'Egypt', 'Algeria', 'Bosnia and Herzegovina', 'Honduras', 'Italy',
       'Greece', "Côte d'Ivoire", 'Chile', 'Paraguay', 'Korea DPR',
       'Slovakia', 'Slovenia', 'South Africa', 'New Zealand', 'Ukraine',
       'Togo', 'Czech Republic', 'Serbia and Montenegro', 'Angola',
       'Trinidad and Tobago', 'Türkiye', 'China PR',
       'Republic of Ireland', 'Romania', 'Scotland', 'FR Yugoslavia',
       'Jamaica', 'Bulgaria', 'Bolivia', 'Norway', 'West Germany',
       'Yugoslavia', 'Czechoslovakia', 'Austria', 'United Arab Emirates',
       'Soviet Union', 'Northern Ireland', 'Iraq', 'Hungary', 'Zaire',
       'Haiti', 'Cuba'], dtype=object)

In [31]:
matche['away_team'].unique()

array(['France', 'Morocco', 'Croatia', 'Portugal', 'Brazil', 'Argentina',
       'Spain', 'Switzerland', 'Korea Republic', 'Poland', 'Senegal',
       'United States', 'Australia', 'Uruguay', 'Belgium', 'Germany',
       'Denmark', 'Mexico', 'Qatar', 'England', 'Serbia', 'Ghana',
       'Costa Rica', 'Canada', 'Saudi Arabia', 'IR Iran', 'Ecuador',
       'Cameroon', 'Japan', 'Tunisia', 'Netherlands', 'Wales', 'Russia',
       'Colombia', 'Sweden', 'Peru', 'Egypt', 'Panama', 'Iceland',
       'Nigeria', 'Algeria', 'Greece', 'Chile', "Côte d'Ivoire",
       'Bosnia and Herzegovina', 'Honduras', 'Italy', 'Slovakia',
       'New Zealand', 'South Africa', 'Korea DPR', 'Paraguay', 'Slovenia',
       'Ukraine', 'Angola', 'Serbia and Montenegro',
       'Trinidad and Tobago', 'Togo', 'Czech Republic', 'Türkiye',
       'Republic of Ireland', 'China PR', 'FR Yugoslavia', 'Norway',
       'Jamaica', 'Bulgaria', 'Austria', 'Scotland', 'Romania', 'Bolivia',
       'Czechoslovakia', 'Yugoslavia', 'United Arab Emirates',
       'Soviet Union', 'West Germany', 'Iraq', 'Northern Ireland',
       'Hungary', 'Kuwait', 'El Salvador', 'Germany DR', 'Haiti', 'Zaire',
       'Israel', 'Cuba', 'Dutch East Indies'], dtype=object)

In [32]:
matche['away_team'] = matche['away_team'].apply(lambda x: x.replace("Korea Republic","Korea DPR"))
matche['away_team'].unique()

array(['France', 'Morocco', 'Croatia', 'Portugal', 'Brazil', 'Argentina',
       'Spain', 'Switzerland', 'Korea DPR', 'Poland', 'Senegal',
       'United States', 'Australia', 'Uruguay', 'Belgium', 'Germany',
       'Denmark', 'Mexico', 'Qatar', 'England', 'Serbia', 'Ghana',
       'Costa Rica', 'Canada', 'Saudi Arabia', 'IR Iran', 'Ecuador',
       'Cameroon', 'Japan', 'Tunisia', 'Netherlands', 'Wales', 'Russia',
       'Colombia', 'Sweden', 'Peru', 'Egypt', 'Panama', 'Iceland',
       'Nigeria', 'Algeria', 'Greece', 'Chile', "Côte d'Ivoire",
       'Bosnia and Herzegovina', 'Honduras', 'Italy', 'Slovakia',
       'New Zealand', 'South Africa', 'Paraguay', 'Slovenia', 'Ukraine',
       'Angola', 'Serbia and Montenegro', 'Trinidad and Tobago', 'Togo',
       'Czech Republic', 'Türkiye', 'Republic of Ireland', 'China PR',
       'FR Yugoslavia', 'Norway', 'Jamaica', 'Bulgaria', 'Austria',
       'Scotland', 'Romania', 'Bolivia', 'Czechoslovakia', 'Yugoslavia',
       'United Arab Emirates', 'Soviet Union', 'West Germany', 'Iraq',
       'Northern Ireland', 'Hungary', 'Kuwait', 'El Salvador',
       'Germany DR', 'Haiti', 'Zaire', 'Israel', 'Cuba',
       'Dutch East Indies'], dtype=object)

In [59]:
matche.iloc[:,1:]

,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,away_manager,...,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long,h_total,a_total
0,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,Didier Deschamps,...,NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...,7.0,5.0
1,Morocco,2,0.7,0.0,1,1.2,0.0,Zlatko Dalić,Luka Modrić,Hoalid Regragui,...,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...,2.0,1.0
2,Morocco,2,2.0,0.0,0,0.9,0.0,Didier Deschamps,Hugo Lloris,Hoalid Regragui,...,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...,2.0,0.0
3,Croatia,3,2.3,0.0,0,0.5,0.0,Lionel Scaloni,Lionel Messi,Zlatko Dalić,...,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',...",3.0,0.0
4,Portugal,1,1.4,0.0,0,0.9,0.0,Hoalid Regragui,Romain Saïss,Fernando Santos,...,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,France,1,NaN,0.0,0,NaN,0.0,Francisco Olazar,Manuel Ferreira,Raoul Caudron,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
960,Brazil,2,NaN,0.0,1,NaN,0.0,Bosko Simonovic,Milutin Ivković,Pindaro De Carvalho,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0
961,Peru,3,NaN,0.0,1,NaN,0.0,Octav Luchide,Emerich Vogl,Francisco Bru,...,NaN,Plácido Galindo · 70,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
962,Belgium,3,NaN,0.0,0,NaN,0.0,Bob Millar,Tom Florie,Hector Goetinck,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0
963,Mexico,4,NaN,0.0,1,NaN,0.0,Raoul Caudron,Alexandre Villaplane,Juan Luque,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0

# EDA

In [34]:
matche.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    object
 1   away_team                        964 non-null    object
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    object
 9   home_captain                     644 non-null    object
 10  away_manager                     964 non-null    object
 11  away_captain                     644 non-null    object
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    object
 14  Officials                        709 non-null    object
 15  Round                            964 non-null    object
 16  Date                             964 non-null    object
 17  Score                            964 non-null    object
 18  Referee                          709 non-null    object
 19  Notes                            73 non-null     object
 20  Host                             964 non-null    object
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    object
 23  away_goal                        571 non-null    object
 24  home_goal_long                   718 non-null    object
 25  away_goal_long                   571 non-null    object
 26  home_own_goal                    39 non-null     object
 27  away_own_goal                    17 non-null     object
 28  home_penalty_goal                116 non-null    object
 29  away_penalty_goal                84 non-null     object
 30  home_penalty_miss_long           6 non-null      object
 31  away_penalty_miss_long           9 non-null      object
 32  home_penalty_shootout_goal_long  34 non-null     object
 33  away_penalty_shootout_goal_long  34 non-null     object
 34  home_penalty_shootout_miss_long  24 non-null     object
 35  away_penalty_shootout_miss_long  30 non-null     object
 36  home_red_card                    51 non-null     object
 37  away_red_card                    54 non-null     object
 38  home_yellow_red_card             23 non-null     object
 39  away_yellow_red_card             31 non-null     object
 40  home_yellow_card_long            621 non-null    object
 41  away_yellow_card_long            627 non-null    object
 42  home_substitute_in_long          740 non-null    object
 43  away_substitute_in_long          747 non-null    object
dtypes: float64(4), int64(4), object(36)
memory usage: 331.5+ KB

In [35]:
matche.head()

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

# 1.simple stat
## total matches
## average goal
## total attendence
## average attendence

In [36]:
# Total number of matches
print(f"Total number of Matches : {len(matche)}")

# Total goal score (penalty score)
print(f"Total goal score : {sum(matche['home_score'] + matche['away_score'])}")

# Average goal score per matche
print(f"Average goal score : {sum(matche['home_score'] + matche['away_score'])/len(matche)}")

# Total Attendence over time
print(f"Total Attendence over time : {sum(matche['Attendance'])}")

# Averge of Attendence over time
print(f"Averge of Attendence over time : {sum(matche['Attendance'])/len(matche)}")

Total number of Matches : 964
Total goal score : 2720
Average goal score : 2.8215767634854774
Total Attendence over time : 44048413
Averge of Attendence over time : 45693.3744813278

# Time a particular country is winner , first runner up and second

In [37]:
world_cup.head()

,Year,Host,Teams,Champion,Runner-Up,TopScorrer,Attendance,AttendanceAvg,Matches
0,2022,Qatar,32,Argentina,France,Kylian Mbappé - 8,3404252,53191,64
1,2018,Russia,32,France,Croatia,Harry Kane - 6,3031768,47371,64
2,2014,Brazil,32,Germany,Argentina,James Rodríguez - 6,3429873,53592,64
3,2010,South Africa,32,Spain,Netherlands,"Wesley Sneijder, Thomas Müller... - 5",3178856,49670,64
4,2006,Germany,32,Italy,France,Miroslav Klose - 5,3352605,52384,64

In [38]:
winner = world_cup['Champion'].value_counts().reset_index() # (reset_index) to data convert in the dataframe
winner

       Champion  count
0        Brazil      5
1         Italy      4
2     Argentina      3
3        France      2
4       Germany      2
5  West Germany      2
6       Uruguay      2
7         Spain      1
8       England      1

# visulization with pie chart

In [39]:
fig = px.pie(winner, values='count', names='Champion', title='Winner')

# Customize the pie chart
fig.update_traces(textinfo = 'label + value')

fig.show()

In [40]:
matche.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    object
 1   away_team                        964 non-null    object
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    object
 9   home_captain                     644 non-null    object
 10  away_manager                     964 non-null    object
 11  away_captain                     644 non-null    object
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    object
 14  Officials                        709 non-null    object
 15  Round                            964 non-null    object
 16  Date                             964 non-null    object
 17  Score                            964 non-null    object
 18  Referee                          709 non-null    object
 19  Notes                            73 non-null     object
 20  Host                             964 non-null    object
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    object
 23  away_goal                        571 non-null    object
 24  home_goal_long                   718 non-null    object
 25  away_goal_long                   571 non-null    object
 26  home_own_goal                    39 non-null     object
 27  away_own_goal                    17 non-null     object
 28  home_penalty_goal                116 non-null    object
 29  away_penalty_goal                84 non-null     object
 30  home_penalty_miss_long           6 non-null      object
 31  away_penalty_miss_long           9 non-null      object
 32  home_penalty_shootout_goal_long  34 non-null     object
 33  away_penalty_shootout_goal_long  34 non-null     object
 34  home_penalty_shootout_miss_long  24 non-null     object
 35  away_penalty_shootout_miss_long  30 non-null     object
 36  home_red_card                    51 non-null     object
 37  away_red_card                    54 non-null     object
 38  home_yellow_red_card             23 non-null     object
 39  away_yellow_red_card             31 non-null     object
 40  home_yellow_card_long            621 non-null    object
 41  away_yellow_card_long            627 non-null    object
 42  home_substitute_in_long          740 non-null    object
 43  away_substitute_in_long          747 non-null    object
dtypes: float64(4), int64(4), object(36)
memory usage: 331.5+ KB

In [41]:
matche.head()

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

In [42]:
matche['Round'].unique()

array(['Final', 'Third-place match', 'Semi-finals', 'Quarter-finals',
       'Round of 16', 'Group stage', 'Second group stage',
       'First group stage', 'Second round', 'First round',
       'Group stage play-off', 'Final stage'], dtype=object)

In [43]:
matche['home_penalty'].fillna(0, inplace=True)
matche['away_penalty'].fillna(0, inplace=True)

<ipython-input-43-a032a6c16c33>:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



<ipython-input-43-a032a6c16c33>:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [44]:
matche.head()

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,0.0,1,1.2,0.0,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,0.0,0,0.9,0.0,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,0.0,0,0.5,0.0,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,0.0,0,0.9,0.0,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

In [45]:
matche['h_total'] = matche['home_score'] + matche['home_penalty']
matche['a_total'] = matche['away_score'] + matche['away_penalty']

In [46]:
matche['h_total'].unique()

array([ 7.,  2.,  3.,  1.,  5.,  6.,  4.,  0.,  8., 10.,  9.])

In [47]:
Runner = matche[matche['Round'] == 'final']
Third = matche[matche['Round'] == 'Third-place match']

In [48]:
# Runner up team
def runner_up(row):
  if (row['h_total'] > row['a_total']):
    return row['away_team']
  else:
    return row['home_team']

# third up team
def third_up(row):
  if (row['h_total'] > row['a_total']):
    return row['away_team']
  else:
    return row['home_team']

In [49]:
Runner['runner_up'] = Runner.apply(runner_up, axis=1)
Third['Third_place'] = Third.apply(third_up, axis=1)

<ipython-input-49-d34740942297>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [50]:
Runner['runner_up'].value_counts().index

Index([], dtype='float64', name='runner_up')

In [51]:
exp = go.Bar(x=Runner['runner_up'].value_counts().index, y=Runner['runner_up'].value_counts().values ,title='first runner up')
exp.show()

ValueError: Invalid property specified for object of type plotly.graph_objs.Bar: 'title'

Did you mean "type"?

    Valid properties:
        alignmentgroup
            Set several traces linked to the same position axis or
            matching axes to the same alignmentgroup. This controls
            whether bars compute their positional range dependently
            or independently.
        base
            Sets where the bar base is drawn (in position axis
            units). In "stack" or "relative" barmode, traces that
            set "base" will be excluded and drawn in "overlay" mode
            instead.
        basesrc
            Sets the source reference on Chart Studio Cloud for
            `base`.
        cliponaxis
            Determines whether the text nodes are clipped about the
            subplot axes. To show the text nodes above axis lines
            and tick labels, make sure to set `xaxis.layer` and
            `yaxis.layer` to *below traces*.
        constraintext
            Constrain the size of text inside or outside a bar to
            be no larger than the bar itself.
        customdata
            Assigns extra data each datum. This may be useful when
            listening to hover, click and selection events. Note
            that, "scatter" traces also appends customdata items in
            the markers DOM elements
        customdatasrc
            Sets the source reference on Chart Studio Cloud for
            `customdata`.
        dx
            Sets the x coordinate step. See `x0` for more info.
        dy
            Sets the y coordinate step. See `y0` for more info.
        error_x
            :class:`plotly.graph_objects.bar.ErrorX` instance or
            dict with compatible properties
        error_y
            :class:`plotly.graph_objects.bar.ErrorY` instance or
            dict with compatible properties
        hoverinfo
            Determines which trace information appear on hover. If
            `none` or `skip` are set, no information is displayed
            upon hovering. But, if `none` is set, click and hover
            events are still fired.
        hoverinfosrc
            Sets the source reference on Chart Studio Cloud for
            `hoverinfo`.
        hoverlabel
            :class:`plotly.graph_objects.bar.Hoverlabel` instance
            or dict with compatible properties
        hovertemplate
            Template string used for rendering the information that
            appear on hover box. Note that this will override
            `hoverinfo`. Variables are inserted using %{variable},
            for example "y: %{y}" as well as %{xother}, {%_xother},
            {%_xother_}, {%xother_}. When showing info for several
            points, "xother" will be added to those with different
            x positions from the first point. An underscore before
            or after "(x|y)other" will add a space on that side,
            only when this field is shown. Numbers are formatted
            using d3-format's syntax %{variable:d3-format}, for
            example "Price: %{y:$.2f}".
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format
            for details on the formatting syntax. Dates are
            formatted using d3-time-format's syntax
            %{variable|d3-time-format}, for example "Day:
            %{2019-01-01|%A}". https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format for details on the
            date formatting syntax. The variables available in
            `hovertemplate` are the ones emitted as event data
            described at this link
            https://plotly.com/javascript/plotlyjs-events/#event-
            data. Additionally, every attributes that can be
            specified per-point (the ones that are `arrayOk: true`)
            are available. Finally, the template string has access
            to variables `value` and `label`. Anything contained in
            tag `<extra>` is displayed in the secondary box, for
            example "<extra>{fullData.name}</extra>". To hide the
            secondary box completely, use an empty tag
            `<extra></extra>`.
        hovertemplatesrc
            Sets the source reference on Chart Studio Cloud for
            `hovertemplate`.
        hovertext
            Sets hover text elements associated with each (x,y)
            pair. If a single string, the same string appears over
            all the data points. If an array of string, the items
            are mapped in order to the this trace's (x,y)
            coordinates. To be seen, trace `hoverinfo` must contain
            a "text" flag.
        hovertextsrc
            Sets the source reference on Chart Studio Cloud for
            `hovertext`.
        ids
            Assigns id labels to each datum. These ids for object
            constancy of data points during animation. Should be an
            array of strings, not numbers or any other type.
        idssrc
            Sets the source reference on Chart Studio Cloud for
            `ids`.
        insidetextanchor
            Determines if texts are kept at center or start/end
            points in `textposition` "inside" mode.
        insidetextfont
            Sets the font used for `text` lying inside the bar.
        legend
            Sets the reference to a legend to show this trace in.
            References to these legends are "legend", "legend2",
            "legend3", etc. Settings for these legends are set in
            the layout, under `layout.legend`, `layout.legend2`,
            etc.
        legendgroup
            Sets the legend group for this trace. Traces and shapes
            part of the same legend group hide/show at the same
            time when toggling legend items.
        legendgrouptitle
            :class:`plotly.graph_objects.bar.Legendgrouptitle`
            instance or dict with compatible properties
        legendrank
            Sets the legend rank for this trace. Items and groups
            with smaller ranks are presented on top/left side while
            with "reversed" `legend.traceorder` they are on
            bottom/right side. The default legendrank is 1000, so
            that you can use ranks less than 1000 to place certain
            items before all unranked items, and ranks greater than
            1000 to go after all unranked items. When having
            unranked or equal rank items shapes would be displayed
            after traces i.e. according to their order in data and
            layout.
        legendwidth
            Sets the width (in px or fraction) of the legend for
            this trace.
        marker
            :class:`plotly.graph_objects.bar.Marker` instance or
            dict with compatible properties
        meta
            Assigns extra meta information associated with this
            trace that can be used in various text attributes.
            Attributes such as trace `name`, graph, axis and
            colorbar `title.text`, annotation `text`
            `rangeselector`, `updatemenues` and `sliders` `label`
            text all support `meta`. To access the trace `meta`
            values in an attribute in the same trace, simply use
            `%{meta[i]}` where `i` is the index or key of the
            `meta` item in question. To access trace `meta` in
            layout attributes, use `%{data[n[.meta[i]}` where `i`
            is the index or key of the `meta` and `n` is the trace
            index.
        metasrc
            Sets the source reference on Chart Studio Cloud for
            `meta`.
        name
            Sets the trace name. The trace name appears as the
            legend item and on hover.
        offset
            Shifts the position where the bar is drawn (in position
            axis units). In "group" barmode, traces that set
            "offset" will be excluded and drawn in "overlay" mode
            instead.
        offsetgroup
            Set several traces linked to the same position axis or
            matching axes to the same offsetgroup where bars of the
            same position coordinate will line up.
        offsetsrc
            Sets the source reference on Chart Studio Cloud for
            `offset`.
        opacity
            Sets the opacity of the trace.
        orientation
            Sets the orientation of the bars. With "v" ("h"), the
            value of the each bar spans along the vertical
            (horizontal).
        outsidetextfont
            Sets the font used for `text` lying outside the bar.
        selected
            :class:`plotly.graph_objects.bar.Selected` instance or
            dict with compatible properties
        selectedpoints
            Array containing integer indices of selected points.
            Has an effect only for traces that support selections.
            Note that an empty array means an empty selection where
            the `unselected` are turned on for all points, whereas,
            any other non-array values means no selection all where
            the `selected` and `unselected` styles have no effect.
        showlegend
            Determines whether or not an item corresponding to this
            trace is shown in the legend.
        stream
            :class:`plotly.graph_objects.bar.Stream` instance or
            dict with compatible properties
        text
            Sets text elements associated with each (x,y) pair. If
            a single string, the same string appears over all the
            data points. If an array of string, the items are
            mapped in order to the this trace's (x,y) coordinates.
            If trace `hoverinfo` contains a "text" flag and
            "hovertext" is not set, these elements will be seen in
            the hover labels.
        textangle
            Sets the angle of the tick labels with respect to the
            bar. For example, a `tickangle` of -90 draws the tick
            labels vertically. With "auto" the texts may
            automatically be rotated to fit with the maximum size
            in bars.
        textfont
            Sets the font used for `text`.
        textposition
            Specifies the location of the `text`. "inside"
            positions `text` inside, next to the bar end (rotated
            and scaled if needed). "outside" positions `text`
            outside, next to the bar end (scaled if needed), unless
            there is another bar stacked on this one, then the text
            gets pushed inside. "auto" tries to position `text`
            inside the bar, but if the bar is too small and no bar
            is stacked on this one the text is moved outside. If
            "none", no text appears.
        textpositionsrc
            Sets the source reference on Chart Studio Cloud for
            `textposition`.
        textsrc
            Sets the source reference on Chart Studio Cloud for
            `text`.
        texttemplate
            Template string used for rendering the information text
            that appear on points. Note that this will override
            `textinfo`. Variables are inserted using %{variable},
            for example "y: %{y}". Numbers are formatted using
            d3-format's syntax %{variable:d3-format}, for example
            "Price: %{y:$.2f}".
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format
            for details on the formatting syntax. Dates are
            formatted using d3-time-format's syntax
            %{variable|d3-time-format}, for example "Day:
            %{2019-01-01|%A}". https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format for details on the
            date formatting syntax. Every attributes that can be
            specified per-point (the ones that are `arrayOk: true`)
            are available. Finally, the template string has access
            to variables `value` and `label`.
        texttemplatesrc
            Sets the source reference on Chart Studio Cloud for
            `texttemplate`.
        uid
            Assign an id to this trace, Use this to provide object
            constancy between traces during animations and
            transitions.
        uirevision
            Controls persistence of some user-driven changes to the
            trace: `constraintrange` in `parcoords` traces, as well
            as some `editable: true` modifications such as `name`
            and `colorbar.title`. Defaults to `layout.uirevision`.
            Note that other user-driven trace attribute changes are
            controlled by `layout` attributes: `trace.visible` is
            controlled by `layout.legend.uirevision`,
            `selectedpoints` is controlled by
            `layout.selectionrevision`, and `colorbar.(x|y)`
            (accessible with `config: {editable: true}`) is
            controlled by `layout.editrevision`. Trace changes are
            tracked by `uid`, which only falls back on trace index
            if no `uid` is provided. So if your app can add/remove
            traces before the end of the `data` array, such that
            the same trace has a different index, you can still
            preserve user-driven changes if you give each trace a
            `uid` that stays with it as it moves.
        unselected
            :class:`plotly.graph_objects.bar.Unselected` instance
            or dict with compatible properties
        visible
            Determines whether or not this trace is visible. If
            "legendonly", the trace is not drawn, but can appear as
            a legend item (provided that the legend itself is
            visible).
        width
            Sets the bar width (in position axis units).
        widthsrc
            Sets the source reference on Chart Studio Cloud for
            `width`.
        x
            Sets the x coordinates.
        x0
            Alternate to `x`. Builds a linear space of x
            coordinates. Use with `dx` where `x0` is the starting
            coordinate and `dx` the step.
        xaxis
            Sets a reference between this trace's x coordinates and
            a 2D cartesian x axis. If "x" (the default value), the
            x coordinates refer to `layout.xaxis`. If "x2", the x
            coordinates refer to `layout.xaxis2`, and so on.
        xcalendar
            Sets the calendar system to use with `x` date data.
        xhoverformat
            Sets the hover text formatting rulefor `x`  using d3
            formatting mini-languages which are very similar to
            those in Python. For numbers, see:
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format.
            And for dates see: https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format. We add two items to
            d3's date formatter: "%h" for half of the year as a
            decimal number as well as "%{n}f" for fractional
            seconds with n digits. For example, *2016-10-13
            09:15:23.456* with tickformat "%H~%M~%S.%2f" would
            display *09~15~23.46*By default the values are
            formatted using `xaxis.hoverformat`.
        xperiod
            Only relevant when the axis `type` is "date". Sets the
            period positioning in milliseconds or "M<n>" on the x
            axis. Special values in the form of "M<n>" could be
            used to declare the number of months. In this case `n`
            must be a positive integer.
        xperiod0
            Only relevant when the axis `type` is "date". Sets the
            base for period positioning in milliseconds or date
            string on the x0 axis. When `x0period` is round number
            of weeks, the `x0period0` by default would be on a
            Sunday i.e. 2000-01-02, otherwise it would be at
            2000-01-01.
        xperiodalignment
            Only relevant when the axis `type` is "date". Sets the
            alignment of data points on the x axis.
        xsrc
            Sets the source reference on Chart Studio Cloud for
            `x`.
        y
            Sets the y coordinates.
        y0
            Alternate to `y`. Builds a linear space of y
            coordinates. Use with `dy` where `y0` is the starting
            coordinate and `dy` the step.
        yaxis
            Sets a reference between this trace's y coordinates and
            a 2D cartesian y axis. If "y" (the default value), the
            y coordinates refer to `layout.yaxis`. If "y2", the y
            coordinates refer to `layout.yaxis2`, and so on.
        ycalendar
            Sets the calendar system to use with `y` date data.
        yhoverformat
            Sets the hover text formatting rulefor `y`  using d3
            formatting mini-languages which are very similar to
            those in Python. For numbers, see:
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format.
            And for dates see: https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format. We add two items to
            d3's date formatter: "%h" for half of the year as a
            decimal number as well as "%{n}f" for fractional
            seconds with n digits. For example, *2016-10-13
            09:15:23.456* with tickformat "%H~%M~%S.%2f" would
            display *09~15~23.46*By default the values are
            formatted using `yaxis.hoverformat`.
        yperiod
            Only relevant when the axis `type` is "date". Sets the
            period positioning in milliseconds or "M<n>" on the y
            axis. Special values in the form of "M<n>" could be
            used to declare the number of months. In this case `n`
            must be a positive integer.
        yperiod0
            Only relevant when the axis `type` is "date". Sets the
            base for period positioning in milliseconds or date
            string on the y0 axis. When `y0period` is round number
            of weeks, the `y0period0` by default would be on a
            Sunday i.e. 2000-01-02, otherwise it would be at
            2000-01-01.
        yperiodalignment
            Only relevant when the axis `type` is "date". Sets the
            alignment of data points on the y axis.
        ysrc
            Sets the source reference on Chart Studio Cloud for
            `y`.
        zorder
            Sets the layer on which this trace is displayed,
            relative to other SVG traces on the same subplot. SVG
            traces with higher `zorder` appear in front of those
            with lower `zorder`.

Did you mean "type"?

Bad property path:
title
^^^^^